name: Feature Branch

on:
  push:
    branches-ignore:
      - "master"
jobs:
  test:
    name: Run Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Go 1.24
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version: 1.24

      - name: Parser test
        run: go test ./... -v
